name: Github Action API and Web Automation 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  api-web-automation:
    runs-on: ubuntu-latest

    steps:
    # download repo
    - uses: actions/checkout@v4
    
    # setup java
    - name: Set up JDK 11
    - uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # install chrome browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v2.1.0

    # setup gradlew
    - name: Set up gradlew
      run : chmod +x gradlew

    # Execute gradle task api
    - name: API automation
      run : ./gradlew api

    # Execute gradle task web
    - name: WEB automation
      run : ./gradlew web

